[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1
healthcheckPath = "/health"
releaseCommand = "node release.js"
startCommand = "node dist/main"
