-- Adiciona novos papéis ao enum UserRole
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GERENTE';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'SECRETARIA';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'MECANICO';
